version: "3.7"

services:
  flask:
    build: ./flask
    restart: always
    volumes:
      - ./flask:/app
    env_file:
      - .env/development/flask
    expose:
      - 8080

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
