version: "3.7"

services:
  flask:
    build: ./flask
    restart: always
    volumes:
      - ./flask:/app
    env_file:
      - .env/development/flask
      - .env/development/database
    expose:
      - 8080

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env/development/database
    # volumes:
    #   - db_data:/path

# volumes:
#   db_data:
